MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();
        // GET: Urun
        public ActionResult Index()
        {
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }
        
        [HttpGet] 
        public ActionResult YeniUrun()
        {
            //DropDownList kullanımı için
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()

                                             }).ToList();
            ViewBag.dgr = degerler;   // Viewa taşımak için ViewBag nesnesi oluşturuyoruz.
            return View();
        }

        [HttpPost]
        public ActionResult YeniUrun(TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var urunler = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urunler = db.TBLURUNLER.Find(id);
            return View("UrunGetir",urunler);
        }

        public ActionResult Guncelle(TBLURUNLER p1)
        {
            var urun = db.TBLURUNLER.Find(p1.URUNID);
            urun.FIYAT = p1.FIYAT;
            urun.URUNAD = p1.URUNAD;
            urun.URUNKATEGORI = p1.URUNKATEGORI;
            urun.STOK = p1.STOK;
            urun.MARKA = p1.MARKA;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>ÜRÜN ID</th>
        <th>ÜRÜN ADI</th>
        <th>MARKASI</th>
        <th>KATEGORİ</th>
        <th>FİYAT</th>
        <th>STOK</th>
        <th>Sil</th>
        <th>Güncelle</th>
        
    </tr>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <th>@item.URUNID</th>
            <td>@item.URUNAD</td>
            <td>@item.MARKA</td>
            @*Inner Join işlemi. Kategori Id yerine adını getirmek için kullandık.*@
            <td>@item.TBLKATEGORILER.KATEGORIAD</td>
            <td>@item.FIYAT</td>
            <td>@item.STOK</td>
            <td><a href="/Urun/Sil/@item.URUNID" class="btn btn-danger">SİL</a></td>
            <td><a href="Urun/UrunGetir/@item.URUNID" class="btn btn-success">GÜNCELLE</a></td>
        </tr>
        }
    </tbody>
</table>

<a href="/Urun/YeniUrun/" class="btn btn-primary">YENİ ÜRÜN EKLE</a>

MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.TBLURUNLER

@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>UrunGetir Sayfası</h2>
@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.URUNID)
    @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNAD)
    @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MARKA)
    @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNKATEGORI)
    @Html.TextBoxFor(m => m.URUNKATEGORI, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.FIYAT)
    @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.STOK)
    @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })

</div>

    <div>
        <button class="btn btn-warning">Ürün Guncelle </button>

    </div>
}

MvcStok/Views/Urun/YeniUrun.cshtml
@model MvcStok.Models.Entity.TBLURUNLER

@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="URUNAD" />
    </div>
    <div>
        <label>Ürün Kategorisi</label>
        @*Kategorinin bir listeden seçilebilmesi için DropDownList kullanacağız*@
        @Html.DropDownListFor(m=>m.TBLKATEGORILER.KATEGORIID,(List<SelectListItem>)ViewBag.dgr,new { @class="form-control"})
    </div>
    <div>
        <label>Ürün Fiyatı</label>
        <input type="text" class="form-control" name="FIYAT" />
    </div>
    <div>
        <label>Ürün Markası</label>
        <input type="text" class="form-control" name="MARKA" />
    </div>
    <div>
        <label>Stok Adedi</label>
        <input type="text" class="form-control" name="STOK" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Ürün Ekle</button>

    </div>

</form>