MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();
        // GET: Musteri
        public ActionResult Index()
        {
            var degerler = db.TBLMUSTERILER.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var urunler = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var mstr = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", mstr);
        }

        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Müşteri Id</th>
        <th>Müşteri Ad</th>
        <th>Müşteri Soyad</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th>@item.MUSTERIID</th>
            <td>@item.MUSTERIAD</td>
            <td>@item.MUSTERISOYAD</td>
            <td><a href="/Musteri/Sil/@item.MUSTERIID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Musteri/MusteriGetir/@item.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
        </tr>

        }
    </tbody>
</table>

<a href="/Musteri/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>MusteriGetir Sayfası</h2>
@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.MUSTERIID)
    @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERIAD)
    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERISOYAD)
    @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })

</div>

<div>
    <button class="btn btn-warning">Musteri Guncelle </button>

</div>
}

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:red" })
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Müşteri Ekle</button>

    </div>

</form>